apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tbs.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tbs.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.app.springProfile | quote }}
  DB_URL: {{ .Values.db.url | quote }}
  DB_USERNAME: {{ .Values.db.username | quote }}
