apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tbs.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tbs.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgresql.password | quote }}
