-- V1: Create location table

CREATE TABLE location (
    id         UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    city       VARCHAR(120),
    country    VARCHAR(80),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_location_name UNIQUE (name)
);

COMMENT ON TABLE  location           IS 'Physical locations that users can be associated with';
COMMENT ON COLUMN location.id        IS 'Primary key — UUID generated by the database';
COMMENT ON COLUMN location.name      IS 'Unique human-readable name for the location (e.g. "Toronto HQ")';
COMMENT ON COLUMN location.city      IS 'City where this location resides';
COMMENT ON COLUMN location.country   IS 'Country where this location resides';
COMMENT ON COLUMN location.created_at IS 'Row creation timestamp (UTC)';
