-- V2: Create user_detail table
-- Named user_detail to avoid conflict with the PostgreSQL reserved word "user"

CREATE TABLE user_detail (
    id          UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    email       VARCHAR(180) NOT NULL,
    location_id UUID,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_detail_email   UNIQUE (email),
    CONSTRAINT fk_user_detail_location
        FOREIGN KEY (location_id) REFERENCES location (id)
        ON DELETE SET NULL
);

CREATE INDEX idx_user_detail_location_id ON user_detail (location_id);
CREATE INDEX idx_user_detail_email       ON user_detail (email);

COMMENT ON TABLE  user_detail              IS 'Application users with an optional location reference';
COMMENT ON COLUMN user_detail.id           IS 'Primary key — UUID generated by the database';
COMMENT ON COLUMN user_detail.name         IS 'Full display name of the user';
COMMENT ON COLUMN user_detail.email        IS 'Unique email address — used as the business identifier';
COMMENT ON COLUMN user_detail.location_id  IS 'Optional FK to location; NULL means no location assigned';
COMMENT ON COLUMN user_detail.created_at   IS 'Row creation timestamp (UTC)';
